# Generated by Django 5.2.13 on 2026-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
