# Generated by Django 5.2.13 on 2026-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_device_emergency_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
